// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMp2iDCwUkNfuWyQ42nsmGZCJhHbXuYo',
    appId: '1:360887096485:web:695045ade3a1d17cad294c',
    messagingSenderId: '360887096485',
    projectId: 'myportfolio-eb732',
    authDomain: 'myportfolio-eb732.firebaseapp.com',
    storageBucket: 'myportfolio-eb732.appspot.com',
    measurementId: 'G-YW668EZMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOiycjEGjQrQXsiJ2udzX-vBY4SyZtFs',
    appId: '1:360887096485:android:98749f3180c7994cad294c',
    messagingSenderId: '360887096485',
    projectId: 'myportfolio-eb732',
    storageBucket: 'myportfolio-eb732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOGWSSMEfQWroZOND1DarHGF0-TR_ivg',
    appId: '1:360887096485:ios:03d99c6ab2d6f2b0ad294c',
    messagingSenderId: '360887096485',
    projectId: 'myportfolio-eb732',
    storageBucket: 'myportfolio-eb732.appspot.com',
    iosClientId: '360887096485-6dhak3dth71b55k51l5pf8i8sh2ki8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOGWSSMEfQWroZOND1DarHGF0-TR_ivg',
    appId: '1:360887096485:ios:03d99c6ab2d6f2b0ad294c',
    messagingSenderId: '360887096485',
    projectId: 'myportfolio-eb732',
    storageBucket: 'myportfolio-eb732.appspot.com',
    iosClientId: '360887096485-6dhak3dth71b55k51l5pf8i8sh2ki8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
